Fix VBScript compilation error in updater (v1.5.38)
The VBScript launcher was using quadruple quotes which caused:
  Error: Expected end of statement
  Code: 800A0401

Changed from:
  Run ""path"", 0, False
To:
  Run Chr(34) & "path" & Chr(34), 0, False

This properly quotes the batch file path for VBScript execution.